#!/bin/sh
set -eu

PLUMOS_ROOT="${PLUMOS_ROOT:-/mnt/plumos}"
APP_ROOT="${PLUMOS_PORTMASTER_APP_ROOT:-${PLUMOS_ROOT}/apps/portmaster}"
PM_DIR="${APP_ROOT}/upstream/PortMaster"

case "${1:-}" in
  "${PM_DIR}"/libs/*.squashfs) exit 0 ;;
  *) exec /bin/umount "$@" ;;
esac
